### ISSUE TITLE
thanks!! how could we donote to you?

### ISSUE THREAD

**Issue by rocke-dong** [seatgeek/thefuzz#19]
thanks!! how could we donote to you?

**Comment by josegonzalez** [comment]
Hi @rocke-dong! Development of this project is done under the umbrella of SeatGeek, Inc. We recommend you instead donate to a charitable organization of your choice. Here are a couple in case you have need of suggestions:

- [UN Refugee Agency](https://www.unrefugees.org/what-we-do/)
- [Save the Children](https://www.savethechildren.org/)
- [International Committee for the Red Cross](https://www.icrc.org/en/donate)

Thanks and have a nice day!
