### ISSUE TITLE
Search for matches in an array of complex objects.

### ISSUE THREAD

**Issue by matheusfenolio** [seatgeek/thefuzz#2]
Hello :smiley:

Is there any planned feature to find matches inside an array of complex objects? 
I found a library that can do it but using NodeJS with [Fuzzball](https://github.com/nol13/fuzzball.js). It would be nice to have this in python as well

e.g.

![image](https://user-images.githubusercontent.com/37229507/131203026-7a0b17ac-d8eb-44da-8ab1-719a4eede7a3.png)

**Comment by bigtoast** [comment]
Hi Friend,

We have no planned work for this library currently. You are welcome to submit a pull request.

Be well,
Andy
