### ISSUE TITLE
What is the advantage of `thefuzz` over `rapidfuzz`?

### ISSUE THREAD

**Issue by bram-pkg** [seatgeek/thefuzz#61]
From what I can tell, this library mostly wraps functionality already implemented in `rapidfuzz`?

I'm curious what this offers that `rapidfuzz` does not?

**Comment by maxbachmann** [comment]
Nothing really. `fuzzywuzzy` was created a lot earlier. `rapidfuzz` started out as a rewrite of `fuzzywuzz` athat has a more open license and is a lot faster. `thefuzz` is just a renamed version of `fuzzywuzzy`. Nowadays it is a wrapper for `rapidfuzz` that handles some small differences in the API of the two libraries.

New users should probably directly use `rapidfuzz`.

**Comment by bram-pkg** [comment]
That's clear, since we are starting a new project we'll use `rapidfuzz` then. Thank you!
