### ISSUE TITLE
Why the latest version in pypi is still 0.20.0? It's not the MIT license.

### ISSUE THREAD

**Issue by nicework123** [seatgeek/thefuzz#69]
dears,
May I know why the latest version of thefuzz is still 0.20.0(https://pypi.org/project/thefuzz/) with GPL V2 license? 
Could you build the newest version to pypi?

many thanks

**Comment by jtownley** [comment]
This would be a very helpful thing. @johnthedebs @maxbachmann

**Comment by johnthedebs** [comment]
I'm taking a look at this, we should have it updated soon.

**Comment by johnthedebs** [comment]
The latest version has been published to pypi: https://pypi.org/project/thefuzz/
