### ISSUE TITLE
How it is different from it's dependency rapidfuzz?

### ISSUE THREAD

**Issue by banderlog** [seatgeek/thefuzz#77]
What new features thefuzz have?

I was able to identify only the "Partial Token Sort Ratio"

**Comment by maxbachmann** [comment]
`rapidfuzz` was written as a replacement for `fuzzywuzzy`/`thefuzz`. `thefuzz` is mostly a backwards compatible wrapper. You can mostly view the differences by just reading the wrapper code. Notable differences are:
- thefuzz rounds results to integers
- the preprocessing function in thefuzz has a force ascii argument which discards characters with code points between 128 and 256
- the process functions in rapidfuzz always use (choice, score, key) for matches. This key is either a key in a dictionary or the index in a list. thefuzz returns the same for dictionaries, but for lists returns only (choice, score)
- thefuzz has a dedupe function to remove duplicates from a list (but that's less than 10 lines of code so you can always just implement it yourself)

In addition rapidfuzz has a lot of similarity metrics and functions that aren't present in thefuzz.

**Comment by banderlog** [comment]
thank you for the detailed answer
